export const FETCH_ORDERS = 'FETCH_ORDERS';
export const SET_SIZE_FILTER = 'SET_SIZE_FILTER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const ORDER_CREATION_SUCCESS = 'ORDER_CREATION_SUCCESS';
export const ORDER_CREATION_FAILURE = 'ORDER_CREATION_FAILURE';
